# Site settings
title: Haven't Coded In Years
email: jeff@haventcodedinyears.com
description: > # this means to ignore newlines until "baseurl:"
  Jeff Sacco's code learning blog.  All the little tid bits I pick up
  on a daily basis are placed here for others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.haventcodedinyears.com" # the base hostname & protocol for your site
github_username:  jeffsacco
google_username: jeffsacco@gmail.com
keep_files: ['.htaccess']
timezone: America/Toronto

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: contact
    url: /contact

# Build settings
markdown: kramdown
#gems:
#  - jekyll-sitemap
